config/routes.rb
Rails.application.routes.draw do
  get 'items/new'
  
  get  '/new',    to: 'items#new'
  get  '/edit',    to: 'items#edit'
  get  '/update_all',    to: 'items#update_all'
  
  root 'items#index'
  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name,  presence: true, length: { maximum: 100 }
  validates :code, presence: true, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # def show
  #   @item = Item.find(params[:id])
  # end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to '/'
    else
      render '/new'
    end
  end
  
  def index
    @items = Item.all
  end
  
  def edit
    @items = Item.all
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      # Handle a successful update.
    else
      render '/edit'
    end
  end
  def update_all
    Item.all.each{|i|
    i.update_attributes(name: params[:name],code: params[:code])
    }
  end
  
  # def update_all
  #   Item.all.each do 
  #     update
  #   end
  # end

  private

    def item_params
      params.require(:item).permit(:name, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render 'layouts/header_edit' %>
<div class="container">
<h1>edit</h1>
<% @items.each do |item| %>
  <div class="edit-line">
    <%= form_for(item) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :code %>
      <%= f.text_field :code %>
      <%= f.submit "submit", class: "btn" %>
    <% end %>
  </div>
<% end %>
</div>
<%= link_to "save", update_all_path, class: "btn" %>
<%= link_to "back", root_path, class: "btn" %>

app/views/items/index.html.erb
<div class="container">
<h1> Index </h1>
<table>
  <thead>
    <tr>
      <th>ITEM</th>
      <th>CODE</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.code %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to "edit", edit_path, class: "btn" %>
<%= link_to "add", new_path, class: "btn" %>

app/views/items/new.html.erb
<div class="container">
<h1>new item</h1>
<%= form_for(@item) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :code %>
  <%= f.text_field :code %>
  <%= f.submit "add", class: "btn" %>
<% end %>
</div>
<%= link_to "back", root_path, class: "btn" %>

app/views/layouts/_header_edit.html.erb
<header class="header-edit">
  <div class="container">
    <h2 class="info-line">Place holder</h2>
    <div class="options">
      <%= link_to "Discard", root_path, class: "btn btn-secondery" %>
      <%= link_to "Save", update_all_path, class: "btn btn-primary" %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>